---
title: "`r gsub('.+:', '', params$title)`"
subtitle: "Workshop outline"
author  : "`r params$author`"

date    : "`r params$date`"
location: "`r params$location`"

abstract: |
  For several years, psychological science has been facing a crisis of confidence fueled by concerns about low rates of successful replications of empirical findings.
  Different solutions have been proposed to address this issue.
  A key factor in these efforts is increasing transparency and computational reproducibility of psychological research.
  While transparent and computationally reproducible research is not necessarily more replicable, it facilitates replication attempts and helps to foster trust in empirical findings.
  The evolving open science ecosystem provides a variety of tools and services that can be used to implement reproducible research practices.
  Navigating the growing space of tools and practices, however, can be a daunting task.

  Hence, the purpose of this 2 days workshop is to introduce researchers to the essential components of tailored reproducible research workflows as well as the tools for implementing them.
  Combining lectures with practical hands-on sessions, the workshop will focus on data analysis, reporting of results, and sharing data and materials.
  Regarding the tool stack, the workshop will cover version control with Git and writing reports with RMarkdown as key components of a reproducible research workflow, but will also introduce other tools, such as the Open Science Framework (OSF), Docker, and Binder.

output:
  html_document:
    keep_md       : true
    theme         : "spacelab"
    df_print      : "kable"
    toc           : true
    toc_float     : true
---

```{r setup, include = FALSE}
library("rmarkdown")
```

---

## Voraussetzungen

Teilnehmerinnen und Teilnehmer sollten grundlegende Kenntnisse in R und etwas Erfahrung mit RStudio haben.


# Vorbereitungen

### R and RStudio

Bitte stellen Sie sicher, dass Sie eine aktuelle Version von R (≥ 4.0.0) und RStudio verwenden.

### LaTeX

Um das vollständige Funktionsset von `papaja` nutzen zu können, benötigen Sie eine [TeX](http://de.wikipedia.org/wiki/TeX)-Distribution.
Wir empfehlen, dass Sie [TinyTex](https://yihui.name/tinytex/) verwenden, eine LaTeX-Distribution, die für die Verwendung mit R Markdown konzipiert ist.
TinyTex kann wie folgt innerhalb von R installiert werden.


```r
# If necessary, install tinytex R package
if(!requireNamespace("tinytex", quietly = TRUE)) install.packages("tinytex")

# Install TinyTex distribution
tinytex::install_tinytex()
```

Falls Sie möchten, können Sie auch [MikTeX](http://miktex.org/) für Windows, [MacTeX](https://tug.org/mactex/) für Mac oder [TeX Live](http://www.tug.org/texlive/) für Linux verwenden.
Beziehen Sie sich ebenfalls auf das [`papaja` manual](https://crsh.github.io/papaja_man/introduction.html#getting-started) für Anweisungen.


#### `papaja`

`papaja` kann folgendermaßen installiert werden:


```r
# Install latest CRAN release
install.packages("papaja")
```

### Git and GitHub

:::warning
<div style="text-align: center"> 🚧
    <br>
    <p>
        <b>Achtung.</b><br>
    Das Einrichten eines GitHub-Kontos ist für diesen Workshop **nicht zwingend notwendig**. Bei Bedarf kann GitHub während des Workshops eingerichtet werden.
    </p>
    </div>

:::


Wir werden Git für die Versionskontrolle (Änderungsnachverfolgung) und als Werkzeug für die Zusammenarbeit verwenden. Die folgenden Schritte können zunächst entmutigend sein, aber die verlinkten Anleitungen sind ausgezeichnet und sollten Ihnen helfen, sich schnell einzurichten. Sie schaffen das! :)

Gehen Sie folgendermaßen vor:

1. Erstellen Sie ein [GitHub](https://github.com)-Konto
2. Installieren Sie Git (see [instructions](https://happygitwithr.com/install-git.html))
 - Während der Installation von Git, fügen Sie `git bash` zum Windows-Kontextmenü hinzu, indem Sie die entsprechende Option auswählen (dies sollte die Standardeinstellung sein)
3. Konfigurieren Sie Git (see [ instructions](https://happygitwithr.com/hello-git.html))
4. Erstellen Sie einen persönlichen Zugriffstoken für HTTPS (see [instructions](https://happygitwithr.com/https-pat.html))
5. bestätigen Sie, dass Sie eine Verbindung zu GitHub herstellen können (see [instructions](https://happygitwithr.com/push-pull-github.html))

